import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  console.log("STYLES OBJECT", styles)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My new Port! Here&apos;s the <a href="https://www.dakotaheim.com/">Old One</a>
        </h1>

        <p className={styles.description}>
          Gonna add stuff here
        </p>

        <div className={styles.grid}>
          <a href="https://www.dakotaheim.com/" className={styles.card}>
            <h2>About here? &rarr;</h2>
          </a>

          <a href="https://www.dakotaheim.com/" className={styles.card}>
            <h2>Contact maybe? &rarr;</h2>
          </a>

          <a
            href="https://www.dakotaheim.com/"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
